import streamlit as st
import pandas as pd
import base64
import os
import io

# ==========================================
# 1. CONFIGURAÇÃO DE SENHA
# ==========================================
SENHA_ACESSO = "cirurgia123" # Altere para a senha que preferir

def check_password():
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if not st.session_state["password_correct"]:
        st.markdown("### 🔒 Acesso Restrito - Controle de Materiais")
        senha = st.text_input("Digite a senha de acesso", type="password")
        if st.button("Entrar"):
            if senha == SENHA_ACESSO:
                st.session_state["password_correct"] = True
                st.rerun()
            else:
                st.error("Senha incorreta.")
        return False
    return True

if not check_password():
    st.stop()

# ==========================================
# 2. BANCO DE DADOS EMBUTIDO (XLS EXTRAÍDOS)
# ==========================================
# Aqui estão os 94 itens extraídos dos seus arquivos do Flex Lab
B64_CSV = "UHJlZ8OjbyxJdGVtLERlc2NyacOnw6NvLFF1YW50aWRhZGUgRGlzcG9uw612ZWwKNjkuMjAyMywxMCwiVEVMQSAzRCAxMjAgWCAxMjBNTSAtIDAsNiBNTSBFTSBUSVTDgk5JTy4iLDEKNjkuMjAyMyw1MSxQTEFDQSBNQUxIQSAwLjMgWCA4NCBYIDUzTU0gRU0gVElUw4JOSU8uLDEKNjkuMjAyMywxMTUsIlBMQUNBIFRJUE8gVEhSRUFETE9DSyBUUywgMi4wLzIuM01NIFggMjAgRlVST1MgUkVUQSBDT00gU0lTVEVNQSBERSAgVFJBVkFNRU5UTyAtIFBFUkZJTCBERSAyLjBNTSBFTSBUSVRBTklPLiIsMQo2OS4yMDIzLDExNiwiUExBQ0EgVElQTyBUSFJFQURMT0NLIFRTLCAyLjAvMi4zTU0gWCAyNiBGVVJPUyBQUsOJIENVUlZBREEgRElSRVRBIEFOQVRPTUlDQSBDT00gIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtIFBFUkZJTCBERSAyLjBNTSBFTSBUSVRBTklPLiIsMQo2OS4yMDIzLDEzMCwiUExBQ0EgVElQTyBUSFJFQURMT0NLIFRTLCAyLjAvMi4zTU0gWCA0ICsgNCBGVVJPUyBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gIFBFUkZJTCBERSAxLjVNTSBFTiBUSVRBTklPLiIsMQo2OS4yMDIzLDEzOSwiUExBQ0EgVElQTyBUSFJFQURMT0NLIFRTLCAyLjAvMi4zTU0gWCA2IEZVUk9TIFJFVEEgQy9TRUcuIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gLSBQRVJGSUwgREUgMS41TU0gRU0gVElUQU5JTy4iLDIKOTAwNzguMjAyNCwxLEJST0NBIDIuMiAgWCAxMTUgTU0gU0VNIFNUT1AgRU5HQVRFIFNUUllLRVIsMQo5MDA3OC4yMDI0LDIsQlJPQ0EgMi4yIFggMTA1IE1NIFNFTSBTVE9QIEVOR0FURSBTVFJZS0VSLDEKOTAwNzguMjAyNCwzLEJST0NBIDIuMiBYIDcwIE1NIFNFTSBTVE9QIEVOR0FURSAgU1RSWUtFUiwxCjkwMDc4LjIwMjQsNCxQQVJBRlVTTyAyLjcgWCAxMU1NIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gRU0gVElUw4JOSU8sMTUKOTAwNzguMjAyNCw1LFBBUkFGVVNPIDIuNyBYIDEzTU0gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVTDgk5JTywxNQo5MDA3OC4yMDI0LDYsUEFSQUZVU08gIDIuNyBYIDE1TU0gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVTDgk5JTywxNQo5MDA3OC4yMDI0LDcsUEFSQUZVU08gMi43IFggMTdNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDUKOTAwNzguMjAyNCw4LFBBUkFGVVNPIDIuNyBYIDdNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDE1CjkwMDc4LjIwMjQsMTAsUExBQ0EgQ1VSVkFEQSBBTkdVTEFEQSBESVJFSVRBIDIuN01NIFggMjYgRlVST1MgLSBQRVJGSUwgREUgMy4wTU0gICAgQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVRBTklPLDEKOTAwNzguMjAyNCwxMyxQTEFDQSBQUsOJIENVUlZBREEgIEFOR1VMQURBICBFU1FVRVJEQSAgMi43TU0gWCAyNiBGVVJPUyAtIFBFUkZJTCAgREUgIDMuME1NIENPTSBTSVNURU1BIERFVFJBVkFNRU5UTyBFTSBUSVRBTklPLDEKOTAwNzguMjAyNCwxNCxQTEFDQSBSRVRBIDIuNyBNTSBYIDEyIEZVUk9TIC0gUEVSRklMIERFIDMuMCBNTSAgIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDE1LFBMQUNBIFJFVEEgMi43IE1NIFggMjAgRlVST1MgLSBQRVJGSUwgREUgMy4wIE1NIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDE2LEJST0NBIDEuMSBYIDEwNSBYIDVNTSBFTkdBVEUgU1RSWUtFUiwxCjkwMDc4LjIwMjQsMTcsQlJPQ0EgMS4xIFggMTA1IFggN01NIEVOR0FURSBTVFJZS0VSLDEKOTAwNzguMjAyNCwxOSxCUk9DQSAxLjEgWCA1MCBYIDE1TU0gRU5HQVRFIFNUUllLRVIsMQo5MDA3OC4yMDI0LDIxLEJST0NBIDEuMSBYIDUwIFggN01NIEVOR0FURSBTVFJZS0VSLDEKOTAwNzguMjAyNCwyMixQQVJBRlVTTyBBVVRPUEVSRlVSQU5URSAxLjUgWCA1IE1NIEVNIFRJVMOCTklPLDI1CjkwMDc4LjIwMjQsMjMsUEFSQUZVU08gQVVUT1BFUkZVUkFOVEUgMS41IFggNyBNTSBFTSBUSVTDgk5JTywyMAo5MDA3OC4yMDI0LDI0LFBBUkFGVVNPIENST1NTIERSSVZFIDEuNSBYIDE1IE1NIEVNIFRJVMOCTklPLDQKOTAwNzguMjAyNCwyNSxQQVJBRlVTTyBDUk9TUyBEUklWRSAxLjUgWCAzLjUgTU0gRU0gVElUw4JOSU8sMgo5MDA3OC4yMDI0LDI2LFBBUkFGVVNPIENST1NTIERSSVZFIDEuNSBYIDVNTSBFTSBUSVRBTklPLDMwCjkwMDc4LjIwMjQsMjcsUEFSQUZVU08gQ1JPU1MgRFJJVkUgMS41IFggNyBNTSBFTSBUSVTDgk5JTywxOQo5MDA3OC4yMDI0LDI4LFBBUkFGVVNPIENST1NTIERSSVZFIDEuNSBYIDkgTU0gRU0gVElUw4JOSU8sMTIKOTAwNzguMjAyNCwyOSxQQVJBRlVTTyBERSBFTUVSR8OKTkNJQSBDUk9TUyBEUklWRSAxLjggIFggNSBNTSBFTSBUSVTDgk5JTyw4CjkwMDc4LjIwMjQsMzAsUEFSQUZVU08gREUgRU1FUkfDik5DSUEgQ1JPU1MgRFJJVkUgMS44ICBYIDcgTU0gRU0gVElUw4JOSU8sNgo5MDA3OC4yMDI0LDMxLFBMQUNBIEFOQVRPTUlDQSAxLjVNTSBQLyBBU1NPQUxITyBERSBPUkJJVEEgQy8gUEVSRklMIERFIDAuM01NIEVNIFRJVEFOSU8sMQo5MDA3OC4yMDI0LDMyLFBMQUNBIEFOQVTDlE1JQ0EgUEFSQSBBU1NPQUxITyBERSBPUkJJVEEgMS41TU0gWCAwLjUgTU0gRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDM3LFBMQUNBIEVNIEwgMS41IE1NICBYIDcgRlVST1MgRElSRUlUQSBBTkdVTE8gMTAwIMKwIEVNIFRJVMOCTklPLDIKOTAwNzguMjAyNCwzOCxQTEFDQSBFTSBMIDEuNSBNTSBYIDcgRlVST1MgRVNRVUVSREEgw4JOR1VMTyAxMDDCsCAgRU0gVElUw4JOSU8sMgo5MDA3OC4yMDI0LDM5LFBMQUNBIFBSw4ktTU9MREFEQSBQQVJBIE1BWElMQSAxLjVNTSBYIDVNTSBFU1FVRVJEQSBFTSBUSVRBTklPLDIKOTAwNzguMjAyNCw0MCxQTEFDQSBQUsOJLU1PTERBREEgUEFSQSBNQVhJTEFSIDEuNSBNTSBYIDUgTU0gRElSRUlUQSBFTSBUSVTDgk5JTywxCjkwMDc4LjIwMjQsNDEsUExBQ0EgUFLDiS1NT0xEQURBIFBBUkEgTUFYSUxBUiAxLjUgTU0gWCA3IE1NIERJUkVJVEEgIEVNIFRJVMOCTklPLDEKOTAwNzguMjAyNCw0MixQTEFDQSBQUsOJLU1PTERBREEgUEFSQSBNQVhJTEFSIDEuNSBNTSBYIDcgTU0gRVNRVUVSREEgRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDQzLFBMQUNBIFBSw4ktTU9MREFEQSBQQVJBIE1BWElMQVIgMS41IE1NIFggOSBNTSBESVJFSVRBICBFTSBUSVTDgk5JTywxCjkwMDc4LjIwMjQsNDQsUExBQ0EgUFLDiS1NT0xEQURBIFBBUkEgTUFYSUxBUiAxLjUgTU0gWCA5IE1NIEVTUVVFUkRBIEVNIFRJVMOCTklPLDEKOTAwNzguMjAyNCw0NixQTEFDQSBQUsOJLU1PTERBREEgUEFSQSBNRU5UTyAxLjUgTU0gWCAxIE1NICBFTSBUSVTDgk5JTywxCjkwMDc4LjIwMjQsNDcsUExBQ0EgUFLDiS1NT0xEQURBIFBBUkEgTUVOVE8gMS41IE1NIFggMyBNTSAgRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDQ5LFBMQUNBIE9SQklUQUwgMS41TU0gWCAxMCBGVVJPUyBFTSBUSVRBTklPLDEKOTAwNzguMjAyNCw1MCxQTEFDQSBPUkJJVEFMIDEuNU1NIFggOCBGVVJPUyBFTSBUSVRBTklPLDEKOTAwNzguMjAyNCw1MSxQTEFDQSBQQVJBIEFTU09BTEhPIERFIMOTUkJJVEEgR1JBTkRFIDEuNU1NIFggMC4zTU0gRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDEzNiwiUEFSQUZVU08gQ1JPU1MgRFJJVkUgMi4wTU0gWCA1TU0gRU0gVElUw4JOSU8gLCIsMTEKOTAwNzguMjAyNCwxMzgsIlBBUkFGVVNPIENST1NTIERSSVZFIDIuME1NIFggOU1NIEVNIFRJVMOCTklPICwiLDEKOTAwNzguMjAyNCwxNDAsIlBBUkFGVVNPIERFIEVNRVJHw4pOQ0lBIENST1NTIERSSVZFIDIuM01NIFggNU1NIEVNIFRJVMOCTklPICwiLDYKOTAwNzguMjAyNCwxNDEsIlBBUkFGVVNPIERFIEVNRVJHw4pOQ0lBIENST1NTIERSSVZFIDIuM01NIFggN01NIEVNIFRJVMOCTklPICwiLDYKOTAwNzguMjAyNCwxNDIsIlBBUkFGVVNPIERFIEVNRVJHw4pOQ0lBIENST1NTIERSSVZFIDIuM01NIFggOU1NIEVNIFRJVMOCTklPICwiLDYKOTAwNzguMjAyNCwxNDMsIlBMQUNBIENPTkRJTEFSIDIuMCBNTSBYIDQgRlVST1MgUkVUQSAtIFBFUkZJTCBERSAxLjAgTU0gRU0gVElUw4JOSU8gLCIsMgo5MDA3OC4yMDI0LDE0NCxQTEFDQSBFTSBMIFBBUkEgRElSRUlUQSAyLjAgTU0gWCA1IEZVUk9TIENPTSAxMDDCsCAtIFBFUkZJTCBERSAwLjcgTU0gRU0gVElUw4JOSU8sMgo5MDA3OC4yMDI0LDE0NSxQTEFDQSBFTSBMIFBBUkEgRElSRUlUQSAyLjBNTSBYIDQgRlVST1MgQ09NIFNFR01FTlRPIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVMOCTklPLDIKOTAwNzguMjAyNCwxNDYsUExBQ0EgRU0gTCBQQVJBIEVTUVVFUkRBIDIuMCBNTSBYIDUgRlVST1MgQ09NIDEwMMKwIC0gUEVSRklMIERFIDAuNyBNTSBFTSBUSVTDgk5JTywyCjkwMDc4LjIwMjQsMTQ3LFBMQUNBIEVNIEwgUEFSQSBFU1FVRVJEQSAyLjBNTSBYIDQgRlVST1MgQ09NIFNFR01FTlRPIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVMOCTklPLDIKOTAwNzguMjAyNCwxNDgsUExBQ0EgRU0gVCAyLjAgTU0gWCA1IEZVUk9TIENPTSBBTkdVTE8gODDCsCBYIDEwMMKwIC0gUEVSRklMIERFIDEuMCBNTSBFTSBUSVTDgk5JTywxCjkwMDc4LjIwMjQsMTQ5LFBMQUNBIEVNIFQgMi4wIE1NIFggNiBGVVJPUyAtIFBFUkZJTCBERSAxLjAgTU0gRU0gVElUw4JOSU8sMQo5MDA3OC4yMDI0LDE1MCxQTEFDQSBSRVRBIDIuME1NIFggMTYgRlVST1MgLSBQRVJGSUwgREUgMS4wTU0gRU0gVElUQU5JTywyCjkwMDc4LjIwMjQsMTUxLFBMQUNBIFJFVEEgMi4wTU0gWCA0IEZVUk9TIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVEFOSU8sMQo5MDA3OC4yMDI0LDE1MyxQTEFDQSBSRVRBIDIuME1NIFggNiBGVVJPUyBDT00gU0VHTUVOVE8gLSBQRVJGSUwgREUgMS4wTU0gRU0gVElUQU5JTywxCjkwMDc4LjIwMjQsMTU0LFBMQUNBIFJFVEEgMi4wTU0gWCA4IEZVUk9TIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVEFOSU8sMQo5MDA3OC4yMDI0LDE1NSxQTEFDQSBTQUdJVEFMIDIuMCBNTSBYIDQgRlVST1MgUkVUQSAtIFBFUkZJTCBERSAxLjAgTU0gRU0gVElUw4JOSU8sMgo5MDA3OC4yMDI0LDE1NixQTEFDQSBFTSBMIFBBUkEgRElSRUlUQSAyLjAgTU0gWCA3IEZVUk9TIENPTSAxMDDCuiAtIFBFUkZJTCBERSAwLjcgTU0gRU0gVElUw4JOSU8sMgo5MDA3OC4yMDI0LDE2NixCUk9DQSAxLjUgWCAxMTVNTSBTRU0gU1RPUCBFTkdBVEUgU1RSWUtFUiwyCjkwMDc4LjIwMjQsMTY3LFBBUkFGVVNPIDIuMCBYIDdNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDMwCjkwMDc4LjIwMjQsMTY4LFBBUkFGVVNPIDIuMCBYIDExTU0gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVTDgk5JTywxNwo5MDA3OC4yMDI0LDE2OSxQQVJBRlVTTyAyLjAgWCAxM01NIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gRU0gVElUw4JOSU8sMjAKOTAwNzguMjAyNCwxNzAsUEFSQUZVU08gMi4wIFggMTVNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDIwCjkwMDc4LjIwMjQsMTcxLFBBUkFGVVNPIDIuMCBYIDVNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDQwCjkwMDc4LjIwMjQsMTcyLFBBUkFGVVNPIDIuMCBYIDlNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDIwCjkwMDc4LjIwMjQsMTczLFBBUkFGVVNPIDIuMyBYIDExTU0gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVTDgk5JTywyMAo5MDA3OC4yMDI0LDE3NCxQQVJBRlVTTyAyLjMgWCAxM01NIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gRU0gVElUw4JOSU8sMjAKOTAwNzguMjAyNCwxNzUsUEFSQUZVU08gMi4zIFggMTVNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDIwCjkwMDc4LjIwMjQsMTc2LFBBUkFGVVNPIDIuMyBYIDVNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDQwCjkwMDc4LjIwMjQsMTc3LFBBUkFGVVNPIDIuMyBYIDdNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDMwCjkwMDc4LjIwMjQsMTc4LFBBUkFGVVNPIDIuMyBYIDlNTSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIEVNIFRJVMOCTklPLDMwCjkwMDc4LjIwMjQsMTc5LFBMQUNBICAyLjAvMi4zTU0gWCAxMiBGVVJPUyBSRVRBTkdVTEFSIENPTSBTSVNURU1BIERFICBUUkFWQU1FTlRPIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVEFOSU8sNQo5MDA3OC4yMDI0LDE4MCxQTEFDQSAyLjAgLyAyLjMgTU0gWCA2IEZVUk9TIFNFTUlMVU5BUiBDLyBTRUcuIE3DiURJTyBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gUEVSRklMIERFIDEuMCBNTSBFTSBUSVRBTklPLDQKOTAwNzguMjAyNCwxODEsUExBQ0EgMi4wLzIuMyBYIDYgRlVST1MgUkVUQSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVEFOSU8sNAo5MDA3OC4yMDI0LDE4MixQTEFDQSAyLjAvMi4zTU0gWCAxMiBGVVJPUyBSRVRBTkdVTEFSIFNFTUlMVU5BUiBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gUEVSRklMIERFIDEuME1NIEVNIFRJVEFOSU8sMgo5MDA3OC4yMDI0LDE4MyxQTEFDQSAyLjAvMi4zTU0gWCAxNCBGVVJPUyBSRVRBIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8g4oCTIFBFUkZJTCBERSAxLjBNTSBFTSBUSVRBTklPLDIKOTAwNzguMjAyNCwxODQsUExBQ0EgMi4wLzIuM01NIFggMjAgRlVST1MgUkVUQSBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gUEVSRklMIERFIDIuME1NIEVNIFRJVEFOSU8sMgo5MDA3OC4yMDI0LDE4NSxQTEFDQSAyLjAvMi4zTU0gWCAyNiBGVVJPUyAgUFLDiSBDVVJWQURBIERJUkVUQSBBTkFUT01JQ0EgQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtICBQRVJGSUwgIERFIDIuME1NIEVNIFRJVEFOSU8sMgo5MDA3OC4yMDI0LDE4NixQTEFDQSAyLjAvMi4zTU0gWCAyNiBGVVJPUyBQUsOJIENVUlZBREEgRVNRVUVSREEgQU5BVE9NSUNBIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gLSBQRVJGSUwgREUgMi4wIE1NIEVNIFRJVEFOSU8sMgo5MDA3OC4yMDI0LDE4NyxQTEFDQSAyLjAvMi4zTU0gWCA0ICsgNCBGVVJPUyBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIC0gICBQRVJGSUwgREUgMS41TU0gRU4gVElUQU5JTyw0CjkwMDc4LjIwMjQsMTg4LFBMQUNBIDIuMC8yLjNNTSBYIDQgRlVST1MgUkVUQSBDL1NFRy4gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtICBQRVJGSUwgREUgMS41IE1NIEVNIFRJVEFOSU8sNAo5MDA3OC4yMDI0LDE4OSxQTEFDQSAyLjAvMi4zTU0gWCA0IEZVUk9TIFJFVEEgQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtICAgUEVSRklMIERFIDEuNU1NIEVNIFRJVEFOSU8sNAo5MDA3OC4yMDI0LDE5MCxQTEFDQSAyLjAvMi4zTU0gWCA0IEZVUk9TIFNFTUlMVU5BUiBDT00gU0lTVEVNQSBERSBUUkFWQU1FTlRPIOKAkyBQRVJGSUwgREUgMS41TU0gRU0gVElUQU5JTyw0CjkwMDc4LjIwMjQsMTkxLFBMQUNBIDIuMC8yLjNNTSBYIDYgRlVST1MgUkVUQSBDL1NFRy4gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtICAgUEVSRklMIERFIDEuNU1NIEVNIFRJVEFOSU8sNAo5MDA3OC4yMDI0LDE5MixQTEFDQSAyLjAvMi4zTU0gWCA2IEZVUk9TIFNFTUlMVU5BUiBDL1NFRy4gQ1VSVE8gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyAtIFBFUkZJTCBERSAxLjBNTSBFTSBUSVRBTklPLDQKOTAwNzguMjAyNCwxOTMsUExBQ0EgMi4wLzIuM01NIFggNiBGVVJPUyAgU0VNSUxVTkFSIEMvU0VHLiBMT05HTyBDT00gU0lTVEVNQSBERSAgICBUUkFWQU1FTlRPIC0gIFBFUkZJTCAgREUgMS4wTU0gRU0gVElUQU5JTyw0CjkwMDc4LjIwMjQsMTk0LFBMQUNBIDIuMC8yLjNNTSBYIDMyIEZVUk9TIFBSw4ktQ1VSVkFEQSBBTkFUT01JQ0EgLSAgICBQRVJGSUwgREUgMi4wTU0gQ09NIFNJU1RFTUEgREUgVFJBVkFNRU5UTyBFTSBUSVRBTklPLDIKOTAwNzguMjAyNCwxOTUsUExBQ0EgMi4wLzIuM01NIFggNCBGVVJPUyBSRVRBIENPTSBTSVNURU1BIERFIFRSQVZBTUVOVE8gLSAgIFBFUkZJTCBERSAxLjBNTSBFTSBUSVRBTklPLDQK"

if not os.path.exists("estoque_cirurgico.csv"):
    csv_decoded = base64.b64decode(B64_CSV).decode('utf-8')
    with open("estoque_cirurgico.csv", "w", encoding="utf-8") as f:
        f.write(csv_decoded)

if not os.path.exists("cartoes_pacientes.csv"):
    df_empty = pd.DataFrame(columns=["Paciente", "NIP", "Data", "Pregão", "Materiais Usados", "Anotações Específicas"])
    df_empty.to_csv("cartoes_pacientes.csv", index=False)

df_estoque = pd.read_csv("estoque_cirurgico.csv")
df_cartoes = pd.read_csv("cartoes_pacientes.csv")

# ==========================================
# 3. INTERFACE DA APLICAÇÃO
# ==========================================
st.set_page_config(page_title="Gestão de Materiais Cirúrgicos", layout="wide")
st.title("🏥 Gestão de Materiais Cirúrgicos (Pregões 69/23 e 78/24)")

tab1, tab2, tab3 = st.tabs(["🛒 Nova Cirurgia (Subtração)", "📦 Estoque (Tempo Real)", "📂 Cartões de Pacientes"])

with tab1:
    st.header("Registrar Uso em Cirurgia")
    col1, col2, col3 = st.columns(3)
    with col1: paciente = st.text_input("Nome do Paciente")
    with col2: nip = st.text_input("NIP")
    with col3: data_cirurgia = st.date_input("Data da Cirurgia")
    
    pregao_selecionado = st.selectbox("Selecione o Pregão", sorted(df_estoque['Pregão'].astype(str).unique()))
    
    # Filtrar itens que possuem saldo positivo
    df_filtrado = df_estoque[(df_estoque['Pregão'].astype(str) == pregao_selecionado) & (df_estoque['Quantidade Disponível'] > 0)]
    
    materiais_selecionados = st.multiselect("Selecione os Materiais Utilizados", df_filtrado['Descrição'].tolist())
    
    quantidades_usadas = {}
    if materiais_selecionados:
        st.write("**Quantidades Utilizadas:**")
        for mat in materiais_selecionados:
            qtd_disp = int(df_filtrado[df_filtrado['Descrição'] == mat]['Quantidade Disponível'].values[0])
            qtd = st.number_input(f"{mat} (Disponível: {qtd_disp})", min_value=1, max_value=qtd_disp, step=1, key=mat)
            quantidades_usadas[mat] = qtd
            
    anotacoes = st.text_area("Anotações Específicas sobre a Cirurgia (Em Branco)")
    
    if st.button("Salvar Cartão e Atualizar Estoque", type="primary"):
        if paciente and nip and materiais_selecionados:
            # 1. Atualizar o estoque
            for mat, qtd in quantidades_usadas.items():
                idx = df_estoque.index[(df_estoque['Pregão'].astype(str) == pregao_selecionado) & (df_estoque['Descrição'] == mat)].tolist()[0]
                df_estoque.at[idx, 'Quantidade Disponível'] -= qtd
            df_estoque.to_csv("estoque_cirurgico.csv", index=False)
            
            # 2. Gerar o cartão do paciente
            lista_materiais_str = "\n".join([f"{qtd}x {mat}" for mat, qtd in quantidades_usadas.items()])
            novo_cartao = pd.DataFrame([{
                "Paciente": paciente,
                "NIP": nip,
                "Data": data_cirurgia.strftime("%d/%m/%Y"),
                "Pregão": pregao_selecionado,
                "Materiais Usados": lista_materiais_str,
                "Anotações Específicas": anotacoes
            }])
            df_cartoes = pd.concat([df_cartoes, novo_cartao], ignore_index=True)
            df_cartoes.to_csv("cartoes_pacientes.csv", index=False)
            
            st.success(f"✅ Cartão gerado para {paciente} e estoque atualizado com sucesso!")
            st.balloons()
        else:
            st.warning("⚠️ Preencha o nome do paciente, NIP e selecione pelo menos um material.")

with tab2:
    st.header("Estoque Atualizado")
    st.dataframe(df_estoque, use_container_width=True, hide_index=True)

with tab3:
    st.header("Histórico de Cirurgias (Cartões dos Pacientes)")
    st.dataframe(df_cartoes, use_container_width=True, hide_index=True)